### ISSUE TITLE
Maven Repo

### ISSUE THREAD

**Issue by Gillani0** [JCThePants/NucleusFramework#1]
Hi,

The jar file of the project is not accessible through Maven. Cheers

**Comment by JCThePants** [comment]
I guess the version that I wrote in the readme file doesn't work. Try changing `<version>LATEST</version>` to `<version>0.2-SNAPSHOT</version>`.

I'll update the readme on the next push. Let me know if this still doesn't work.

**Comment by Gillani0** [comment]
Worked as a charm. Cheers Mate!!
